baseURL: http://https://joaomiguelrodriguespereira.netlify.app/
languageCode: en-us
title: Portfolio website for Joao Miguel Rodrigues Pereira
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-Where minds are truly brought to life
    title: Joao Miguel Rodrigues Pereira is a Master in Finance Candidate at London Business School (MFA2023) and a First Class Honours graduate in Economics from the University of Surrey. 
  blog: {}
  contact: +351 926 473 698
    address: 
      - city: London
        country: United Kingdom
        street: London Business School
        title: About us 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jpereira.mfa2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+351) 926 473 698
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright:  @2023 Joao Pereira where applicable. Do not distribute or reproduce in whole or in part without written permission of Joao Pereira 
    enable: yes
     quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.london.edu/masters-degrees/student-alumni-and-ambassadors/joao-miguel-rodrigues-pereira
    social:
      #- icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/jomi.pereira.1
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/joaomiguelgcrp/?next=%2F
      - icon: fa-github
        label: GitHub
        url: https://github.com/Joaomiguelgcrp
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/joaomrpereira/
  image: ''
  name: Joao Miguel Rodrigues Pereira
  navigation:
    button1:
      - name: Why choose the University of Surrey?
        url: https://blogs.surrey.ac.uk/student-experience/2022/07/09/why-choose-the-university-of-surrey/
    button2:
      - name: Five things I love about university life
        url: https://blogs.surrey.ac.uk/student-experience/2022/06/25/five-things-i-love-about-university/
    links:
      - name: Economics 101: A Placement in her majesty’s government!
        url: https://blogs.surrey.ac.uk/professional-training-placement-experience/2021/07/06/economics-101-a-placement-in-her-majestys-government/
      - name: Joao Miguel Rodrigues Pereira - London Business School
        url: https://www.london.edu/masters-degrees/student-alumni-and-ambassadors/joao-miguel-rodrigues-pereira
      - name: Joao Miguel Rodrigues Pereira - University of Surrey
        url: https://www.surrey.ac.uk/student-life/what-our-students-say/joao-miguel-rodrigues-pereira
      #- name: Elements
       # url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
